TARGET_HAS_THIRD_PARTY_APPS := true

BOARD_WPA_SUPPLICANT_DRIVER := AWEXT

BOARD_USES_TSLIB := true
BOARD_USES_I915C := true
BOARD_USES_DRM := true

BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true

include $(GENERIC_X86_CONFIG_MK)
